AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template deploys an HTTP API Gateway with three endpoints, each triggering a different Lambda function.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  # HTTP API Gateway
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${EnvironmentName}-http-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        MaxAge: 86400

  # Roles
  ApiGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !ImportValue Upload-FunctionArn
                  - !ImportValue Analysis-FunctionArn
                  - !ImportValue Fix-FunctionArn
        - PolicyName: ApiGatewayLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: "*"

  # Integrations
  UploadIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !ImportValue Upload-FunctionArn
      PayloadFormatVersion: '2.0'
      CredentialsArn: !GetAtt ApiGatewayExecutionRole.Arn

  AnalysisIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !ImportValue Analysis-FunctionArn
      PayloadFormatVersion: '2.0'
      CredentialsArn: !GetAtt ApiGatewayExecutionRole.Arn

  FixIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !ImportValue Fix-FunctionArn
      PayloadFormatVersion: '2.0'
      CredentialsArn: !GetAtt ApiGatewayExecutionRole.Arn

  # Routes for each endpoint
  UploadPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /upload'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /upload'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /upload'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadProxyGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /upload/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadProxyPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /upload/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadProxyPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /upload/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  UploadProxyPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /upload/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref UploadIntegration]]

  AnalysisGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /analysis'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /analysis'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /analysis'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /analysis'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisProxyGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /analysis/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisProxyPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /analysis/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisProxyPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /analysis/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  AnalysisProxyPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /analysis/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref AnalysisIntegration]]

  FixGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /fix'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /fix'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /fix'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /fix'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixProxyGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /fix/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixProxyPutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /fix/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixProxyPatchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PATCH /fix/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  FixProxyPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /fix/{proxy+}'
      Target: !Join ["/", ["integrations", !Ref FixIntegration]]

  # LogGroup
  ApiGatewayLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/http-api'
      RetentionInDays: 10

  # Stage
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGatewayLogs.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'

  # Permissions for API Gateway to invoke each Lambda
  UploadLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue Upload-FunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

  AnalysisLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue Analysis-FunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

  FixLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue Fix-FunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

Outputs:
  ApiEndpoint:
    Description: The HTTP API Gateway base URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  UploadEndpoint:
    Description: The /upload endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/upload'
  AnalysisEndpoint:
    Description: The /upload endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/analysis'
  FixEndpoint:
    Description: The /fix endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/fix'
