AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: LLM Service

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 512
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"

Resources:
  LlmServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: llm-service
      Handler: dist/handler.handler
      CodeUri: .
      Events:
        AnalyzeEndpoint:
          Type: Api
          Properties:
            Path: /llm-service/analyze
            Method: POST
            RestApiId: !Ref LlmApi
      Policies:
        - AWSLambdaBasicExecutionRole

  LlmApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
