AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template deploys a Lambda function using a Docker image, with S3 and DynamoDB access.

Parameters:
  ServiceName:
    Description: Name of the service
    Type: String
    Default: upload
  JwtPrivateKey:
    Description: Private key for the JWT
    Type: String
  JwtPublicKey:
    Description: Public key for the JWT
    Type: String
  SonarOrg:
    Description: Sonar organization name
    Type: String
    Default: devops-software-engineering
  SonarToken:
    Description: Access token to the sonar host 
    Type: String
  SonarHost:
    Type: String
    Default: https://sonarcloud.io
  AnalysisServiceImageUri:
    Description: Uri to the image
    Type: String
  Repo:
    Description: The ECR repository name for the Lambda Docker image
    Type: String
    Default: analysis-service

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Analyses-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - 'arn:aws:s3:::files-upload-stack'
                  - 'arn:aws:s3:::files-upload-stack/*'
        - PolicyName: DynamoDBUploadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:eu-west-1:379245767025:table/Projects-upload-stack
        - PolicyName: DynamoDBAnalysisAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt DynamoDBTable.Arn

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'Analysis-${AWS::StackName}'
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref AnalysisServiceImageUri
      Timeout: 800
      MemorySize: 3000
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue LambdaSecurityGroup
        SubnetIds:
          - !ImportValue PrivateSubnet
      Environment:
        Variables:
          SERVICE_NAME: !Ref ServiceName
          JWT_PRIVATE_KEY: !Ref JwtPrivateKey
          JWT_PUBLIC_KEY: !Ref JwtPublicKey
          SONAR_ORG: !Ref SonarOrg
          SONAR_TOKEN: !Ref SonarToken
          SONAR_HOST: !Ref SonarHost
          S3_BUCKET_NAME: !ImportValue Upload-BucketName
          UPLOAD_TABLE_NAME: !ImportValue Upload-TableName
          ANALYSIS_TABLE_NAME: !Ref DynamoDBTable

Outputs:
  AnalysisArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "Analysis-FunctionArn"
  AnalysisTableArn:
    Description: ARN of the analysis table
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: Analysis-TableArn
  AnalysisTableName:
    Description: Name of the analysis table
    Value: !Ref DynamoDBTable
    Export:
      Name: Analysis-TableName
