AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template deploys a Lambda function using a Docker image.

Parameters:
  FixServiceImageUri:
    Description: Uri to the image
    Type: String
  OpenAIApiKey:
    Description: The key for the OpenAI API
    Type: String
  Repo:
    Description: The ECR repository name for the Lambda Docker image
    Type: String
    Default: fix-service

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'Fix-${AWS::StackName}'
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref FixServiceImageUri
      Timeout: 30
      MemorySize: 128
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue LambdaSecurityGroup
        SubnetIds:
          - !ImportValue PrivateSubnet
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey

Outputs:
  FunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "Fix-FunctionArn"
