name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'apps/services/**'
      - 'apps/llm-service/**'
      - 'apps/analysis-service/**'

env:
  AWS_REGION: eu-west-1

jobs:
  deploy_vpc_stack:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./apps/services/vpc-stack.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./apps/services/vpc-stack.yml \
            --stack-name vpc-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              EnvironmentName=prod

  deploy_upload_stack:
    needs: [deploy_vpc_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Publish Dockerfile
        working-directory: ./apps/services/upload
        run: sh ./publish.sh

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./apps//services/upload/upload-stack.yml

      - name: Deploy CloudFormation
        working-directory: ./apps/services/upload
        run: sh ./deploy.sh

  deploy_fix_stack:
    needs: [deploy_vpc_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Publish Dockerfile
        working-directory: ./apps/llm-service
        run: sh ./publish.sh

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./apps//llm-service/fix-stack.yml

      - name: Deploy CloudFormation
        working-directory: ./apps/llm-service
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: sh ./deploy.sh

  deploy_api_gateway_stack:
    needs: [deploy_upload_stack, deploy_fix_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./apps/services/api-gateway-stack.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./apps/services/api-gateway-stack.yml \
            --stack-name api-gateway-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              EnvironmentName=prod
