name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-frontend.yml"
      - "apps/frontend/**"

env:
  AWS_REGION: eu-west-1

jobs:
  build:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          working-directory: apps/frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./apps/frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: frontend-build
          path: ./apps/frontend/dist

  deploy_stack:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./apps/frontend/frontend-stack.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./apps/frontend/frontend-stack.yml \
            --stack-name frontend-stack \
            --capabilities CAPABILITY_IAM

      - name: Get and print frontend domain
        run: |
          SPADomain=$(aws cloudformation describe-stacks --stack-name frontend-stack --query "Stacks[0].Outputs[?OutputKey=='SPADomain'].OutputValue" --output text)
          echo "SPADomain: $SPADomain"

  upload:
    needs: [build, deploy_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v7
        with:
          name: frontend-build
          path: ./apps/frontend/dist

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name frontend-stack --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text)
          aws s3 sync ./apps/frontend/dist s3://$BUCKET_NAME --delete

      - name: Invalidate CloudFront cache
        run: |
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name frontend-stack --query "Stacks[0].Outputs[?OutputKey=='CFDistributionId'].OutputValue" --output text)
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
