name: Deploy Backend

on:
  push:
    # branches:
    #   - main
    paths:
      - ".github/workflows/deploy-backend.yml"
      - "networking/**"
      - "apps/upload-service/**"
      - "apps/fix-service/**"
      - "apps/analysis-service/**"

env:
  AWS_REGION: eu-west-1
  GIT_HASH: ${{ github.sha }}
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy_vpc_stack:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Networking stack
        uses: ./.github/actions/deploy-networking
        with:
          template-file: ./networking/vpc-stack.yml
          stack-name: vpc-stack
          parameter-overrides: EnvironmentName=prod

  deploy_upload_stack:
    needs: [deploy_vpc_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda service
        uses: ./.github/actions/deploy-lambda
        with:
          working-directory: ./apps/upload-service
          template-file: ./apps/upload-service/upload-stack.yml
          stack-name: upload-service-stack
          parameter-overrides: |
            EnvironmentName=prod
            UploadServiceImageUri=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/upload-service:${{ env.GIT_HASH }}

  deploy_analysis_stack:
    needs: [deploy_vpc_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda service
        uses: ./.github/actions/deploy-lambda
        with:
          working-directory: ./apps/analysis-service
          template-file: ./apps/analysis-service/analysis-stack.yml
          stack-name: analysis-service-stack
          parameter-overrides: |
            EnvironmentName=prod
            AnalysisServiceImageUri=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/analysis-service:${{ env.GIT_HASH }}

  deploy_fix_stack:
    needs: [deploy_vpc_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda service
        uses: ./.github/actions/deploy-lambda
        with:
          working-directory: ./apps/fix-service
          template-file: ./apps/fix-service/fix-stack.yml
          stack-name: fix-service-stack
          parameter-overrides: |
            EnvironmentName=prod
            FixServiceImageUri=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/fix-service:${{ env.GIT_HASH }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}

  deploy_api_gateway_stack:
    needs: [deploy_upload_stack, deploy_fix_stack, deploy_analysis_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Networking stack
        uses: ./.github/actions/deploy-networking
        with:
          template-file: ./networking/api-gateway-stack.yml
          stack-name: api-gateway-stack
          parameter-overrides: EnvironmentName=prod

  deploy_monitoring_stack:
    needs: [deploy_api_gateway_stack]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Networking stack
        uses: ./.github/actions/deploy-networking
        with:
          template-file: ./networking/monitoring-stack.yml
          stack-name: monitoring-stack
          parameter-overrides: EnvironmentName=prod